name: Build

on:
  workflow_call:
    inputs:
      version-number:
        type: string
  workflow_dispatch:
    inputs:
      version-number:
        type: string
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # 64-bit Windows (Intel & AMD)
          - platform: windows-latest
            rust-targets: x86_64-pc-windows-gnu
            tauri-target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        with:
          toolchain: nightly
          targets: ${{ matrix.rust-targets }}

      - uses: swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3
        with:
          shared-key: ${{ matrix.tauri-target }}-${{ hashFiles('Cargo.lock') }}

      - run: pnpm i
      - run: pnpm run --filter zebar --filter @zebar/settings-ui build

      - name: Set version number
        shell: bash
        run: |
          CONF_PATH="packages/desktop/tauri.conf.json"
          cat "$CONF_PATH" | jq '.version="${{ inputs.version-number || '0.0.0' }}"' > "$CONF_PATH.tmp" && \
          mv "$CONF_PATH.tmp" "$CONF_PATH"

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          RFC3161_TIMESTAMP_URL: ${{ vars.RFC3161_TIMESTAMP_URL }}
          VERSION_NUMBER: ${{ inputs.version-number || '0.0.0' }}
        with:
          projectPath: packages/desktop
          args: --target ${{ matrix.tauri-target }}

      - name: Move & rename artifacts
        shell: bash
        run: |
          mkdir tmp
          ARTIFACTS='${{ steps.tauri.outputs.artifactPaths }}'
          for ARTIFACT in $(echo "$ARTIFACTS" | jq -r '.[]'); do
            mv "$ARTIFACT" "tmp/tauri.${ARTIFACT##*.}"
          done

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: bundle-${{ matrix.tauri-target }}
          if-no-files-found: error
          path: tmp
